# file: postgresql/tasks/install_yum.yml

# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).
- name: PostgreSQL | Make sure the CA certificates are available
  yum:
    name: ca-certificates
    state: present

- name: "Create temp directory"
  become: false
  connection: local
  file:
    path: ".tmp/{{inventory_hostname}}"
    state: directory

- name: PostgreSQL | Download repository RPM
  connection: local
  become: false
  get_url:
    dest: ".tmp/{{inventory_hostname}}/postgres_{{ postgresql_version_terse }}_repository.rpm"
    url: "{{ postgresql_yum_repository_url }}"
  changed_when: false
  run_once: true

- name: PostgreSQL | Copy repository RPM to server
  copy: 
    src: ".tmp/{{inventory_hostname}}/postgres_{{ postgresql_version_terse }}_repository.rpm"
    dest: "/tmp//postgres_{{ postgresql_version_terse }}_repository.rpm"

- name: PostgreSQL | Add PostgreSQL repository
  yum:
    name: "/tmp/postgres_{{ postgresql_version_terse }}_repository.rpm"
    state: present

- name: PostgreSQL | Switch to http
  replace:
    dest: "/etc/yum.repos.d/pgdg-{{ postgresql_version_terse }}-redhat.repo"
    regexp: "https"
    replace: "http"
  when: "http_proxy is not none"

- name: PostgreSQL | Add proxy to repo
  lineinfile:
    dest: "/etc/yum.repos.d/pgdg-{{ postgresql_version_terse }}-redhat.repo"
    insertafter: "^{{ item | regex_escape() }}"
    line: "proxy={{ http_proxy }} #{{ item }}"
  with_items:
    - "[pgdg{{ postgresql_version_terse }}]"
    - "[pgdg{{ postgresql_version_terse }}-source]"
  when: "http_proxy is not none"

- name: PostgreSQL | Make sure the dependencies are installed
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: ["python-psycopg2", "python-pycurl", "glibc-common"]

- name: PostgreSQL | Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  environment: "{{ postgresql_env }}"
  with_items:
    - "postgresql{{ postgresql_version_terse }}-server"
    - "postgresql{{ postgresql_version_terse }}"
    - "postgresql{{ postgresql_version_terse }}-contrib"

- name: PostgreSQL | PGTune
  yum:
    name: pgtune
    state: present
  environment: "{{ postgresql_env }}"
  when: postgresql_pgtune
